---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      dnf: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
