---
- hosts: all
  tasks:
      - name: Install nginx web server
        dnf: name=nginx state=installed update_cache=true
     - name start nginx
       service:
       name: nhinx
       state: started
       enable: yes
